import { useState, type FormEvent } from 'react';
import { Bell, BookOpen, Check, CheckCheck, ChevronDown, ExternalLink, Globe2, GraduationCap, Link2, Mail, RefreshCw, Unplug } from 'lucide-react';
import { Empty, ErrorNotice, Field, Spinner, type Translate } from './components';
import { errorMessage, formatDate, timeSetting } from './lib';
import type { AcademicRecord, AuthConfig, Integration, Locale, Notification, User } from './types';

function integrationErrorText(code: string, provider: Integration['provider'], t: Translate) {
  const messages: Record<string, string> = {
    UED_REAUTH_REQUIRED: t('Phiên cổng UED đã hết hạn. Hãy kết nối lại để tiếp tục đồng bộ; dữ liệu đã lưu vẫn được giữ nguyên.', 'Your UED session has expired. Reconnect to keep syncing; saved data is unchanged.'),
    UED_IDENTITY_MISMATCH: t('Phiên UED không còn khớp tài khoản này. Hãy kết nối lại đúng mã sinh viên.', 'This UED session no longer matches the account. Reconnect with the correct student ID.'),
    UED_BROWSER_UNAVAILABLE: t('Máy chủ đồng bộ chưa có trình duyệt tự động. Quản trị viên cần hoàn tất cấu hình Playwright.', 'The sync server does not have its automation browser installed. An administrator must finish Playwright setup.'),
    SYNC_FAILED: t(`Lần đồng bộ ${provider} gần nhất chưa thành công. Dữ liệu cũ vẫn an toàn; hãy thử lại sau.`, `The latest ${provider} sync did not finish. Existing data is safe; try again later.`),
    OUTLOOK_REAUTH_REQUIRED: t('Phiên Microsoft đã hết hạn. Hãy kết nối lại Outlook.', 'Your Microsoft session has expired. Reconnect Outlook.'),
  };
  return messages[code] || t(`Chưa thể đồng bộ ${provider} (${code}). Dữ liệu đã lưu không bị thay đổi.`, `Could not sync ${provider} (${code}). Saved data was not changed.`);
}

function TermControls({ integration, t, locale, save }: { integration: Integration; t: Translate; locale: Locale; save: (body: { mode: 'CURRENT' } | { academicYear: number; semester: number }) => Promise<void> }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const selected = integration.cursor?.uedTerm || integration.cursor?.uedTermChoices?.selected;
  const choices = integration.cursor?.uedTermChoices;
  const act = async (body: { mode: 'CURRENT' } | { academicYear: number; semester: number }) => { setBusy(true); setError(''); try { await save(body); } catch (err) { setError(errorMessage(err, locale)); } finally { setBusy(false); } };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act({ academicYear: Number(form.get('academicYear')), semester: Number(form.get('semester')) }); };
  return <form className="term-form" onSubmit={submit}>{error && <ErrorNotice>{error}</ErrorNotice>}<strong>{t('Học kỳ đồng bộ', 'Sync term')}</strong><p className="muted small">{integration.cursor?.uedTermMode === 'SELECTED' ? t('Đang xem học kỳ bạn chọn. Có thể trở về học kỳ hiện tại của trường.', 'Using your selected term. You can return to the current school term.') : t('Mặc định theo học kỳ hiện tại của trường. Chọn học kỳ cũ để xem lại dữ liệu.', 'Following the current school term by default. Select an earlier term to review your records.')}</p><div className="form-grid"><Field label={t('Năm học', 'Academic year')}>{choices?.academicYears?.length ? <select name="academicYear" defaultValue={selected?.academicYear}>{choices.academicYears.map(year => <option key={year.value} value={year.value}>{year.label}</option>)}</select> : <input name="academicYear" type="number" min={2000} max={2100} required defaultValue={selected?.academicYear || new Date().getFullYear()} />}</Field><Field label={t('Học kỳ', 'Semester')}><select name="semester" defaultValue={selected?.semester || 1}>{choices?.semesters?.length ? choices.semesters.map(semester => <option key={semester.value} value={semester.value}>{semester.label}</option>) : [1, 2, 3].map(semester => <option key={semester} value={semester}>{t('Học kỳ', 'Semester')} {semester}</option>)}</select></Field></div><div className="detail-actions"><button className="button button-secondary small-button" disabled={busy}>{busy ? <Spinner /> : <Check size={14} />}{t('Xem học kỳ này', 'Use this term')}</button><button type="button" className="button button-quiet small-button" disabled={busy} onClick={() => act({ mode: 'CURRENT' })}>{t('Học kỳ hiện tại', 'Current term')}</button></div></form>;
}
function AcademicFields({ data, t }: { data: Record<string, unknown>; t: Translate }) {
  const labels: Record<string, string> = { course: t('Học phần', 'Course'), courseCode: t('Mã học phần', 'Course code'), courseName: t('Tên học phần', 'Course name'), class: t('Lớp', 'Class'), classCode: t('Lớp học phần', 'Class code'), credits: t('Số tín chỉ', 'Credits'), teacher: t('Giảng viên', 'Lecturer'), lecturer: t('Giảng viên', 'Lecturer'), room: t('Phòng học', 'Room'), location: t('Địa điểm', 'Location'), day: t('Thứ', 'Day'), weekday: t('Thứ', 'Weekday'), periods: t('Tiết học', 'Periods'), period: t('Tiết học', 'Period'), weeks: t('Tuần học', 'Teaching weeks'), week: t('Tuần', 'Week'), academicYear: t('Năm học', 'Academic year'), semester: t('Học kỳ', 'Semester'), grade: t('Điểm', 'Grade'), score: t('Điểm', 'Score'), attendance: t('Điểm danh', 'Attendance'), title: t('Tiêu đề', 'Title'), content: t('Nội dung', 'Content'), date: t('Ngày', 'Date'), source: t('Nguồn', 'Source'), syncedAt: t('Đồng bộ lúc', 'Synced at') };
  const readable = (value: unknown): React.ReactNode => {
    if (value === null || value === undefined || value === '') return '—';
    if (Array.isArray(value)) return <ul className="evidence-list">{value.map((item, index) => <li key={index}>{readable(item)}</li>)}</ul>;
    if (typeof value === 'object') return <dl>{Object.entries(value as Record<string, unknown>).map(([key, item]) => <div key={key}><dt>{labels[key] || key}</dt><dd>{readable(item)}</dd></div>)}</dl>;
    if (typeof value === 'boolean') return value ? t('Có', 'Yes') : t('Không', 'No');
    return String(value);
  };
  const content = data.fields && typeof data.fields === 'object' && !Array.isArray(data.fields) ? { ...(data.fields as Record<string, unknown>), ...(data.academicYear ? { academicYear: data.academicYear } : {}), ...(data.semester ? { semester: data.semester } : {}) } : data;
  return <dl>{Object.entries(content).filter(([key]) => !/token|cookie|secret|externalId|userId|sourceUrl/i.test(key)).map(([key, value]) => <div key={key}><dt>{labels[key] || key}</dt><dd>{readable(value)}</dd></div>)}</dl>;
}

export function SettingsPage({ user, locale, t, save }: { user: User; locale: Locale; t: Translate; save: (body: Record<string, unknown>) => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); setError(''); setSaved(false);
    try {
      const activeStartTime = String(f.get('activeStartTime')), activeEndTime = String(f.get('activeEndTime')), breakStartTime = String(f.get('breakStartTime')), breakEndTime = String(f.get('breakEndTime'));
      if (activeStartTime >= activeEndTime) throw new Error(t('Giờ hoạt động phải bắt đầu trước khi kết thúc trong cùng ngày.', 'Active hours must start before they end on the same day.'));
      if (breakStartTime >= breakEndTime || breakStartTime < activeStartTime || breakEndTime > activeEndTime) throw new Error(t('Giờ nghỉ phải nằm trọn trong giờ hoạt động và bắt đầu trước khi kết thúc.', 'Your break must fall within active hours and start before it ends.'));
      const timezone = String(f.get('timezone')).trim();
      try { new Intl.DateTimeFormat('en', { timeZone: timezone }).format(); } catch { throw new Error(t('Múi giờ không hợp lệ.', 'Invalid timezone.')); }
      await save({ name: String(f.get('name')).trim(), activeStartTime, activeEndTime, breakStartTime, breakEndTime, timezone, minBlockMinutes: Number(f.get('minBlockMinutes')), travelMinutes: Number(f.get('travelMinutes')), studyLocation: String(f.get('studyLocation')).trim() || null, locale: f.get('locale'), notificationsEnabled: f.get('notificationsEnabled') === 'on' }); setSaved(true);
    } catch (err) { setError(errorMessage(err, locale)); } finally { setBusy(false); }
  };
  return <form onSubmit={submit} className="settings-form" onChange={() => setSaved(false)}>
    {error && <ErrorNotice>{error}</ErrorNotice>}
    <section className="panel settings-section"><div className="section-explanation"><span className="section-kicker">01 / {t('THÓI QUEN', 'YOUR ROUTINE')}</span><h2>{t('Một ngày theo cách của bạn', 'Your day, your way')}</h2><p>{t('Những khung giờ này chỉ áp dụng khi gợi ý lịch. Sự kiện bạn đã xác nhận vẫn được giữ nguyên.', 'These hours guide future suggestions. Your confirmed calendar stays in place.')}</p></div><div className="settings-fields"><div className="form-grid"><Field label={t('Bắt đầu ngày', 'Active from')}><input type="time" name="activeStartTime" required defaultValue={timeSetting(user.activeStartTime)} /></Field><Field label={t('Kết thúc ngày', 'Active until')}><input type="time" name="activeEndTime" required defaultValue={timeSetting(user.activeEndTime)} /></Field></div><div className="form-grid"><Field label={t('Bắt đầu nghỉ', 'Break starts')}><input type="time" name="breakStartTime" required defaultValue={timeSetting(user.breakStartTime)} /></Field><Field label={t('Kết thúc nghỉ', 'Break ends')}><input type="time" name="breakEndTime" required defaultValue={timeSetting(user.breakEndTime)} /></Field></div><Field label={t('Múi giờ', 'Timezone')} hint={t('Lịch và deadline luôn được hiển thị theo múi giờ này.', 'Your calendar and deadlines always use this timezone.')}><input name="timezone" required maxLength={64} list="timezones" defaultValue={user.timezone} /><datalist id="timezones"><option value="Asia/Ho_Chi_Minh" /><option value="Asia/Singapore" /><option value="Asia/Tokyo" /><option value="Europe/London" /><option value="America/New_York" /><option value="UTC" /></datalist></Field></div></section>
    <section className="panel settings-section"><div className="section-explanation"><span className="section-kicker">02 / {t('TẬP TRUNG', 'FOCUS')}</span><h2>{t('Đủ thời gian để vào nhịp', 'Room to find your focus')}</h2><p>{t('Không chen lịch vào giờ nghỉ. Luôn tính đến thời gian di chuyển giữa các địa điểm.', 'Breaks stay free. Travel time is included between different locations.')}</p></div><div className="settings-fields"><div className="form-grid"><Field label={t('Phiên học tối thiểu (phút)', 'Minimum session (minutes)')} hint={t('Từ 15 đến 120 phút.', 'Between 15 and 120 minutes.')}><input type="number" min={15} max={120} step={1} required name="minBlockMinutes" defaultValue={user.minBlockMinutes} /></Field><Field label={t('Di chuyển (phút)', 'Travel time (minutes)')}><input type="number" min={0} max={120} step={1} required name="travelMinutes" defaultValue={user.travelMinutes} /></Field></div><Field label={t('Nơi học thường xuyên', 'Usual study location')} hint={t('Cùng địa điểm đã biết có thể không cần đệm di chuyển.', 'A known shared location can skip the travel buffer.')}><input name="studyLocation" maxLength={255} defaultValue={user.studyLocation || ''} placeholder={t('Ví dụ: Thư viện UED', 'e.g. UED Library')} /></Field></div></section>
    <section className="panel settings-section"><div className="section-explanation"><span className="section-kicker">03 / {t('CÁ NHÂN HÓA', 'PREFERENCES')}</span><h2>{t('Gần gũi với bạn hơn', 'Make yourself at home')}</h2><p>{t('Thông báo nằm ngay trong ứng dụng để bạn chủ động xem lại và quyết định.', 'Notifications live in the app so you can review and decide in your own time.')}</p></div><div className="settings-fields"><Field label={t('Tên hiển thị', 'Display name')}><input name="name" required maxLength={120} defaultValue={user.name} /></Field><Field label={t('Ngôn ngữ', 'Language')}><select name="locale" defaultValue={locale}><option value="vi">Tiếng Việt</option><option value="en">English</option></select></Field><label className="checkbox-row"><input type="checkbox" name="notificationsEnabled" defaultChecked={user.notificationsEnabled} /><span><strong>{t('Nhận thông báo trong ứng dụng', 'In-app notifications')}</strong><small>{t('Cập nhật đồng bộ, đề xuất và nhắc việc.', 'Sync updates, suggestions, and reminders.')}</small></span></label></div></section>
    <div className="settings-save">{saved && <span className="saved-message" role="status"><CheckCheck size={17} />{t('Đã lưu tùy chỉnh của bạn.', 'Your preferences are saved.')}</span>}<button className="button button-primary" type="submit" disabled={busy}>{busy ? <Spinner /> : <Check size={17} />}{t('Lưu tùy chỉnh', 'Save preferences')}</button></div>
  </form>;
}
export function NotificationsPage({ notifications, locale, user, t, read, busy }: { notifications: Notification[]; locale: Locale; user: User; t: Translate; read: (id?: string) => void; busy: boolean }) {
  return <section className="panel"><div className="panel-heading"><div><h2>{t('Hộp thư cập nhật', 'Your updates')}</h2><p>{t('Mọi điều cần biết, trong một nơi.', 'Everything you need to know, in one place.')}</p></div><button className="button button-quiet small-button" disabled={busy || !notifications.some(n => !n.readAt)} onClick={() => read()}><CheckCheck size={16} />{t('Đọc tất cả', 'Mark all read')}</button></div>
    {notifications.length ? <div className="notification-list">{notifications.map(n => <article className={`notification-row ${n.readAt ? '' : 'unread'}`} key={n.id}><span className="notification-icon"><Bell size={19} /></span><div className="notification-copy"><h3>{locale === 'vi' ? n.titleVi : n.titleEn}{!n.readAt && <span className="unread-dot" />}</h3><p>{locale === 'vi' ? n.bodyVi : n.bodyEn}</p><small>{formatDate(n.createdAt, user.timezone, 'dd/MM/yyyy · HH:mm', locale)}</small></div>{!n.readAt && <button className="icon-button" aria-label={t('Đánh dấu đã đọc', 'Mark as read')} title={t('Đánh dấu đã đọc', 'Mark as read')} disabled={busy} onClick={() => read(n.id)}><Check size={18} /></button>}</article>)}</div> : <Empty icon={<Bell size={25} />} title={t('Bạn đã cập nhật mọi thứ', "You're all caught up")} description={t('Thông báo mới sẽ xuất hiện ở đây.', 'New notifications will appear here.')} />}
  </section>;
}
export function IntegrationsPage({ integrations, records, config, user, locale, t, sync, disconnect, connectUed, busy, saveTerm }: { integrations: Integration[]; records: AcademicRecord[]; config: AuthConfig; user: User; locale: Locale; t: Translate; sync: (provider: string) => void; disconnect: (provider: string) => void; connectUed: () => void; busy: boolean; saveTerm: (body: {mode: 'CURRENT'} | {academicYear: number; semester: number}) => Promise<void> }) {
  const [category, setCategory] = useState('all');
  const stateLabel = (state: string) => ({ CONNECTED: t('Đã kết nối', 'Connected'), REAUTH_REQUIRED: t('Cần xác thực lại', 'Sign in again'), ERROR: t('Cần kiểm tra', 'Needs attention'), DISCONNECTED: t('Chưa kết nối', 'Not connected') })[state] || state;
  const categories = [...new Set(records.map(r => r.category))];
  return <div className="page-stack"><div className="integration-grid">{(['UED', 'OUTLOOK'] as const).map(provider => { const current = integrations.find(i => i.provider === provider); const status = current?.status || 'DISCONNECTED'; return <section className="panel integration-card" key={provider}><div className="integration-top"><span className={`integration-logo ${provider.toLowerCase()}`}>{provider === 'UED' ? <GraduationCap size={30} /> : <Mail size={28} />}</span><span className={`badge state-${status.toLowerCase()}`}>{stateLabel(status)}</span></div><h2>{provider === 'UED' ? t('Cổng sinh viên UED', 'UED student portal') : 'Microsoft Outlook'}</h2><p>{provider === 'UED' ? t('Hiện đồng bộ thời khóa biểu đã xác minh. Lịch thi, điểm và dữ liệu khác chỉ xuất hiện sau khi được kiểm chứng an toàn trên cổng trường.', 'Currently syncs the verified timetable. Exams, grades, and other records appear only after their portal mappings are safely verified.') : t('Theo dõi email tiếng Việt và tiếng Anh để phát hiện thay đổi lớp học. Bạn xác nhận trước khi cập nhật lịch.', 'Read Vietnamese and English emails for class changes. You confirm before your calendar is updated.')}</p><div className="integration-information"><span><Check size={14} />{provider === 'UED' ? t('Mã sinh viên · Phiên đăng nhập mã hóa', 'Student ID · Encrypted session') : t('Email trường · Microsoft OAuth', 'School email · Microsoft OAuth')}</span><span><Check size={14} />{t('Chỉ đọc dữ liệu của bạn', 'Read-only access to your data')}</span></div>{current?.lastSyncAt && <small className="muted">{t('Đồng bộ lần cuối', 'Last synced')}: {formatDate(current.lastSyncAt, user.timezone, 'dd/MM HH:mm', locale)}</small>}{current?.lastError && <div className="callout callout-amber" role="status">{integrationErrorText(current.lastError, provider, t)}</div>}
      {provider === 'UED' && status === 'CONNECTED' && <TermControls key={`${current?.cursor?.uedTerm?.academicYear}-${current?.cursor?.uedTerm?.semester}-${current?.cursor?.uedTermMode}`} integration={current!} t={t} locale={locale} save={saveTerm} />}<div className="integration-actions">{status === 'CONNECTED' ? <><button className="button button-secondary" disabled={busy} onClick={() => sync(provider)}><RefreshCw size={15} />{t('Đồng bộ', 'Sync now')}</button><button className="icon-button" disabled={busy} onClick={() => disconnect(provider)} aria-label={t('Ngắt kết nối', 'Disconnect')} title={t('Ngắt kết nối', 'Disconnect')}><Unplug size={18} /></button></> : provider === 'OUTLOOK' && config.microsoftEnabled && !user.isDemo ? <a className="button button-primary" href="/api/v1/integrations/outlook/connect"><Link2 size={16} />{status === 'REAUTH_REQUIRED' ? t('Kết nối lại Outlook', 'Reconnect Outlook') : t('Kết nối Outlook', 'Connect Outlook')}</a> : provider === 'UED' && config.uedEnabled && !user.isDemo ? <button className="button button-primary" onClick={connectUed}><Link2 size={16} />{status === 'REAUTH_REQUIRED' ? t('Xác thực lại UED', 'Reconnect UED') : t('Kết nối UED', 'Connect UED')}</button> : <span className="setup-note">{user.isDemo ? t('Kết nối tài khoản thật sau khi đăng nhập bằng tài khoản trường.', 'Sign in with your school account to connect real integrations.') : provider === 'UED' ? t('Kết nối sẽ sẵn sàng sau khi cổng UED được cấu hình.', 'Connection becomes available after UED portal setup.') : t('Kết nối sẽ sẵn sàng sau khi ứng dụng Microsoft được cấu hình.', 'Connection becomes available after Microsoft app setup.')}</span>}</div>{provider === 'UED' && <a className="text-link external-link" href="https://qlht.ued.udn.vn/" target="_blank" rel="noreferrer">{t('Mở cổng sinh viên', 'Open student portal')}<ExternalLink size={13} /></a>}</section>; })}</div>
    <section className="panel"><div className="panel-heading"><div><div className="heading-inline"><BookOpen size={19} /><h2>{t('Dữ liệu học tập', 'Academic records')}</h2></div><p>{t('Dữ liệu đã đồng bộ từ tài khoản trường của bạn.', 'Records synced from your own student account.')}</p></div>{categories.length > 0 && <select aria-label={t('Lọc loại dữ liệu', 'Filter record type')} value={category} onChange={e => setCategory(e.target.value)}><option value="all">{t('Tất cả', 'All records')}</option>{categories.map(c => <option value={c} key={c}>{c}</option>)}</select>}</div>{records.length ? <div className="records-list">{records.filter(r => category === 'all' || r.category === category).map(record => <details className="record" key={record.id}><summary><span><strong>{record.title}</strong><small>{record.category} · {formatDate(record.syncedAt, user.timezone, 'dd/MM HH:mm', locale)}</small></span><ChevronDown size={17} /></summary><AcademicFields data={record.data} t={t} /></details>)}</div> : <Empty icon={<GraduationCap size={26} />} title={t('Kết nối với hành trình học tập', 'Connect your academic journey')} description={t('Sau khi liên kết UED, thời khóa biểu và dữ liệu thực tế sẽ xuất hiện tại đây.', 'Once UED is connected, your timetable and actual academic records will appear here.')} />}</section>
    <div className="quiet-note"><Globe2 size={17} /><span>{t('Bạn kiểm soát quyền truy cập. Có thể ngắt kết nối bất cứ lúc nào; các lịch đã chấp nhận vẫn được giữ lại.', 'You control access. Disconnect at any time; previously accepted calendar events are kept.')}</span></div>
  </div>;
}
