import { useState } from 'react';
import { CalendarDays, Check, MapPin, Pencil, RefreshCw } from 'lucide-react';
import { ConfirmDialog, ErrorNotice, Modal, Spinner, type Translate } from './components';
import { errorMessage, formatDate } from './lib';
import { isPersonalEvent } from './calendar-data';
import type { CalendarEvent, Locale, User } from './types';

type Context = { user: User; locale: Locale; t: Translate };
export function EventDetails({ event, user, locale, t, close, edit, status }: Context & { event: CalendarEvent; close: () => void; edit: (event: CalendarEvent) => void; status: (event: CalendarEvent, status: CalendarEvent['status']) => Promise<void> }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [confirmCancel, setConfirmCancel] = useState(false);
  const act = async (value: CalendarEvent['status']) => { setBusy(true); setError(''); try { await status(event, value); } catch (err) { setError(errorMessage(err, locale)); } finally { setBusy(false); } };
  const readOnly = !isPersonalEvent(event);
  return <>
    <Modal className="calendar-event-detail" title={event.title} onClose={close} busy={busy}><div className="form-stack">{error && <ErrorNotice>{error}</ErrorNotice>}<div className="detail-badges"><span className="badge">{event.eventType === 'CLASS' ? t('Lớp học', 'Class') : event.eventType === 'DEADLINE' ? 'Deadline' : t('Cá nhân', 'Personal')}</span><span className="badge">{event.status === 'CANCELLED' ? t('Đã hủy', 'Cancelled') : event.status === 'COMPLETED' ? t('Đã hoàn thành', 'Completed') : t('Đã lên lịch', 'Scheduled')}</span>{event.source === 'SCHOOL_PORTAL' && <span className="badge state-connected">{t('Cố định từ UED', 'Fixed from UED')}</span>}</div><div className="detail-line"><CalendarDays size={18} /><span>{formatDate(event.startTime, user.timezone, 'EEEE, dd/MM/yyyy HH:mm', locale)}<br />{t('đến', 'to')} {formatDate(event.endTime, user.timezone, 'dd/MM/yyyy HH:mm', locale)}<small>{user.timezone}</small></span></div><div className="detail-line"><MapPin size={18} /><span>{event.location || t('Chưa có địa điểm', 'No location')}</span></div>{event.source !== 'MANUAL' && <div className="callout">{t('Nguồn', 'Source')}: {event.source === 'SCHOOL_PORTAL' ? 'UED' : event.source}. {event.source === 'SCHOOL_PORTAL' ? t('Lịch học UED chỉ được xem, không chỉnh sửa thủ công. Thay đổi từ nguồn đồng bộ cần bạn xác nhận.', 'UED classes are read-only. Changes from the connected source require your confirmation.') : t('Chỉnh sửa ở đây chỉ thay đổi lịch cá nhân của bạn.', 'Changes here only affect your personal calendar.')}</div>}{readOnly && event.source !== 'SCHOOL_PORTAL' && <div className="callout">{t('Mục lịch nguồn cũ chỉ được xem. Không có liên kết công việc để sửa deadline từ mục này.', 'This legacy calendar item is read-only. It has no task link for editing a deadline.')}</div>}{!readOnly && <div className="detail-actions"><button className="button button-secondary" onClick={() => edit(event)} disabled={busy}><Pencil size={16} />{t('Chỉnh sửa', 'Edit')}</button>{event.status === 'SCHEDULED' ? <><button className="button button-primary" disabled={busy} onClick={() => act('COMPLETED')}>{busy ? <Spinner /> : <Check size={16} />}{t('Đã hoàn thành', 'Mark complete')}</button><button className="button button-danger" disabled={busy} onClick={() => setConfirmCancel(true)}>{t('Hủy lịch', 'Cancel event')}</button></> : <button className="button button-primary" disabled={busy} onClick={() => act('SCHEDULED')}><RefreshCw size={16} />{t('Khôi phục lịch', 'Restore event')}</button>}</div>}</div></Modal>
    {confirmCancel && <ConfirmDialog title={t('Hủy lịch cá nhân', 'Cancel personal event')} message={t('Hủy sự kiện này trong lịch cá nhân?', 'Cancel this event in your personal calendar?')} confirmLabel={t('Hủy sự kiện', 'Cancel event')} cancelLabel={t('Giữ lại', 'Keep')} danger busy={busy} onConfirm={async () => { await act('CANCELLED'); setConfirmCancel(false); }} onCancel={() => setConfirmCancel(false)} />}
  </>;
}
