export {
  Prisma,
  PrismaClient,
  type User,
  type Event,
  type Task,
  type TaskScheduleBlock,
  type Session,
  type OAuthAttempt,
  type Suggestion,
  type Notification,
  type Integration,
  type AcademicRecord,
  EventType,
  EventStatus,
  EventSource,
  TaskPriority,
  TaskStatus,
  TaskBlockStatus,
  TaskBlockOrigin,
  SuggestionStatus,
  SuggestionKind,
  IntegrationProvider,
  IntegrationStatus,
} from "./generated/prisma/client.js";
export { getPrismaClient } from "./client.js";
